version: 0.2
phases:
  pre_build:
    commands:
      - echo Running tests...
      - go test *.go
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t gohackday:latest .
      - docker tag gohackday:latest 911610643236.dkr.ecr.eu-west-1.amazonaws.com/gohackday:latest
  post_build:
    commands:
      - echo Build completed on `date`
